### PR TITLE
Treat macOS keychain like iOS keychain.

### PR DESCRIPTION
**Pull request by arunthotta-okta**
Please see https://github.com/okta/okta-devices-swift/pull/57 for detailed description for a similar change.

### CODE REVIEW

**Comment by arunthotta-okta** [comment]
@IldarAbdullin-okta might need your help for the release steps.

**Comment by IldarAbdullin-okta** [comment]
@arunthotta-okta , there are compilation errors for test target. Could you please check?

**Comment by arunthotta-okta** [comment]
@IldarAbdullin-okta was able to get past the build errors if I bump up Xcode version. looking into some test failures now. seeing same failures locally. debugging now. 

also first time dealing with travis :)

**Comment by arunthotta-okta** [comment]
weird because the changes should be a no-op for the iOS test scheme

**Pull request merged**
